### ISSUE TITLE
Redes Sociales

### ISSUE THREAD

**Issue by YitzakEmileZam** [PachamancaUwu/healthycannab#36]

**Comment by MichaelG003** [comment]
![Image](https://github.com/user-attachments/assets/3f594e3a-1e4c-4288-a8be-4c2a1baf6979)
![Image](https://github.com/user-attachments/assets/886ae768-772d-471d-8a70-aa6a45cbc4ec)
![Image](https://github.com/user-attachments/assets/924ec06b-65bb-44a3-bbc4-fdd5e41046e7)
![Image](https://github.com/user-attachments/assets/73798e1a-25a2-4220-a06f-5a8c2214bbe2)
